### ISSUE TITLE
 `ActionUpdateThread.OLD_EDT` is deprecated error pops up in PhpStorm 2024.2.3

### ISSUE THREAD

**Issue by dpinncoder** [liying2008/git-conflict#13]
After upgrading PhpStorm to version 2024.2.3, getting the following error when looking at a file with git merge conflicts.  Choosing Highlight Git Conflicts still seems to work, as does Fixing the conflict..

But, still get this error pop up here and there.  Sometimes when opening a page with conflicts.. sometimes when highlighting conflicts, but seems to work on second try?  

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'cc.duduhuo.git.conflict.action.HighlightConflictAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: cc.duduhuo.git-conflict]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by liying2008** [comment]
@dpinncoder Thank you for reporting this issue, please upgrade to version 2.0.1 to resolve this issue.

**Comment by dpinncoder** [comment]
Hey, thanks for being so responsive and updating your plugin!  Appreciate it!
