### ISSUE TITLE
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 

### ISSUE THREAD

**Issue by VarunAgw** [liying2008/git-conflict#15]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'cc.duduhuo.git.conflict.action.HighlightConflictAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: cc.duduhuo.git-conflict]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

![image](https://github.com/user-attachments/assets/76f159f5-f0f4-4ed6-bdcc-62b507172817)

**Comment by liying2008** [comment]
@VarunAgw Please upgrade to version 2.0.1 to resolve this issue.
